compiler = g++
executable_flag = -o
warning_flags = -Wall -Werror

compile:
	$(compiler) $(warning_flags) $(executable_flag) inheritance inheritance.cpp

run: compile inheritance
	./inheritance

clean:
	rm -rf *.o inheritance
