compiler = gcc
warningFlags = -Wall -Werror
debuggingFlag = -g

run:	compile U101114FCS203
	./U101114FCS203
	
compile:
	$(compiler) $(warningFlags) $(debuggingFlag) -o U101114FCS203 U101114FCS203.c
	
clean:
	rm -r U101114FCS203
